Table TAXI_TRIPS_CONSISTENT {
  VENDOR_ID VARCHAR
  TPEP_PICKUP_DATETIME TIMESTAMP_NTZ
  TPEP_DROPOFF_DATETIME TIMESTAMP_NTZ
  PASSENGER_COUNT FLOAT
  TRIP_DISTANCE FLOAT
  PICKUP_LONGITUDE NUMBER(18,15)
  PICKUP_LATITUDE NUMBER(18,15)
  RATECODE_ID NUMBER(38,0)
  STORE_AND_FWD_FLAG VARCHAR
  DROPOFF_LONGITUDE NUMBER(18,15)
  DROPOFF_LATITUDE NUMBER(18,15)
  PAYMENT_TYPE NUMBER(3,0)
  FARE_AMOUNT NUMBER(10,2)
  EXTRA NUMBER(10,2)
  MTA_TAX NUMBER(10,2)
  TIP_AMOUNT NUMBER(10,2)
  TOLLS_AMOUNT NUMBER(10,2)
  IMPROVEMENT_SURCHARGE NUMBER(10,2)
  TOTAL_AMOUNT NUMBER(10,2)
  TRIP_DURATION_MINUTES NUMBER(4,0)
  TRIP_SPEED_MPH NUMBER(5,2)
  CREATED_TIMESTAMP TIMESTAMP_NTZ
}

Table FACT_TAXI_TRIPS {
  VENDOR_ID VARCHAR
  PAYMENT_TYPE_ID VARCHAR
  PICKUP_DATE_ID VARCHAR
  DROPOFF_DATE_ID VARCHAR
  PICKUP_LOCATION_ID VARCHAR
  DROPOFF_LOCATION_ID VARCHAR
  PASSENGER_COUNT FLOAT
  TRIP_DISTANCE FLOAT
  FARE_AMOUNT NUMBER(10,2)
  EXTRA NUMBER(10,2)
  MTA_TAX NUMBER(10,2)
  TIP_AMOUNT NUMBER(10,2)
  TOLLS_AMOUNT NUMBER(10,2)
  IMPROVEMENT_SURCHARGE NUMBER(10,2)
  TOTAL_AMOUNT NUMBER(10,2)
  TRIP_DURATION_MINUTES NUMBER(4,0)
  TRIP_SPEED_MPH NUMBER(5,2)
}

TABLE DIM_VENDOR {
  VENDOR_ID VARCHAR [
    primary key,
    ref: < FACT_TAXI_TRIPS.VENDOR_ID
  ]
  VENDOR_NAME VARCHAR
}

Table DIM_PAYMENT_TYPE {
  PAYMENT_TYPE_ID VARCHAR [
    primary key,
    ref: < FACT_TAXI_TRIPS.PAYMENT_TYPE_ID
  ]
  PAYMENT_TYPE_NAME NUMBER(3,0)
}

Table DIM_DATE {
  DATE_ID VARCHAR [
    primary key,
    ref: < FACT_TAXI_TRIPS.PICKUP_DATE_ID,
    ref: < FACT_TAXI_TRIPS.DROPOFF_DATE_ID
  ]
  YEAR NUMBER(4,0)
  MONTH NUMBER(2,0)
  WEEK NUMBER(2,0)
  WEEK_OF_THE_YEAR NUMBER(2,0)
  DATE TIMESTAMP_NTZ
}

Table DIM_LOCATION {
  LOCATION_ID VARCHAR [
    primary key,
    ref: < FACT_TAXI_TRIPS.PICKUP_LOCATION_ID,
    ref: < FACT_TAXI_TRIPS.DROPOFF_LOCATION_ID
  ]
  LATITUDE NUMBER(18,15)
  LONGITUDE NUMBER(18,15)
}
