version: 2

sources:
  - name: taxi_trips
    database: ee_se_de_db
    schema: amitd
    tables:
      - name: taxi_trips_raw
        columns:
          - name: TPEP_PICKUP_DATETIME
            tests:
              - dbt_utils.not_empty_string
          - name: TPEP_DROPOFF_DATETIME
            tests:
              - dbt_utils.not_empty_string
          - name: PICKUP_LONGITUDE
            tests:
              - dbt_utils.not_empty_string
          - name: PICKUP_LATITUDE
            tests:
              - dbt_utils.not_empty_string
      - name: taxi_trips_consistent

models:
  - name: dim_vendor
    description: "Vendor dimension table"
    config:
      materialized: table
      tags: ['taxi_trips']
  - name: taxi_trips_consistent
    description: "Taxi trips consistent cleansed data"
    config:
      materialized: table
      tags: ['taxi_trips']
  - name: stg_taxi_trips_consistent
    description: "Taxi trips consistent stage data"
    config:
      pre_hook:
        sql: "TRUNCATE TABLE STG_TAXI_TRIPS_CONSISTENT;"
        transaction: False
      tags: ['taxi_trips']
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - VENDOR_ID
            - TPEP_PICKUP_DATETIME
            - PICKUP_LONGITUDE
            - PICKUP_LATITUDE
      - dbt_utils.expression_is_true:
          expression: 'TPEP_DROPOFF_DATETIME > TPEP_PICKUP_DATETIME'
          description: 'Dropoff time should be after pickup time'
      - dbt_utils.expression_is_true:
          expression: 'NOT (COALESCE(PICKUP_LATITUDE, 0) = 0 AND COALESCE(PICKUP_LONGITUDE, 0) = 0)'
          description: 'Both PICKUP_LATITUDE and PICKUP_LONGITUDE should not be null or 0'
      - dbt_utils.expression_is_true:
          expression: 'NOT (COALESCE(DROPOFF_LATITUDE, 0) = 0 AND COALESCE(DROPOFF_LONGITUDE, 0) = 0)'
          description: 'Both DROPOFF_LATITUDE and DROPOFF_LONGITUDE should not be null or 0'
    columns:
      - name: VENDOR_ID
        tests:
          - not_null
      - name: TPEP_PICKUP_DATETIME
        tests:
          - not_null
      - name: TPEP_DROPOFF_DATETIME
      - name: PASSENGER_COUNT
      - name: TRIP_DISTANCE
        tests:
          - dbt_utils.expression_is_true:
              expression: '> 0'
      - name: PICKUP_LONGITUDE
      - name: PICKUP_LATITUDE
      - name: RATECODE_ID
      - name: STORE_AND_FWD_FLAG
      - name: DROPOFF_LONGITUDE
      - name: DROPOFF_LATITUDE
      - name: PAYMENT_TYPE
      - name: FARE_AMOUNT
      - name: EXTRA
      - name: MTA_TAX
      - name: TIP_AMOUNT
      - name: TOLLS_AMOUNT
      - name: IMPROVEMENT_SURCHARGE
      - name: TOTAL_AMOUNT
      - name: TRIP_DURATION_MINUTES
      - name: TRIP_SPEED_MPH
      - name: CREATED_TIMESTAMP
