{{
    config(
        materialized = 'incremental',
        unique_key = ['VENDOR_ID', 'TPEP_PICKUP_DATETIME', 'PICKUP_LONGITUDE', 'PICKUP_LATITUDE'],
        on_schema_change = 'sync_all_columns',
        incremental_strategy = 'merge'
    )
}}

WITH STG_SOURCE AS (
    SELECT
        VENDOR_NAME AS VENDOR_ID,
        TPEP_PICKUP_DATETIME::TIMESTAMP_NTZ AS TPEP_PICKUP_DATETIME,
        TPEP_DROPOFF_DATETIME::TIMESTAMP_NTZ AS TPEP_DROPOFF_DATETIME,
        PASSENGER_COUNT::NUMBER(2,0) AS PASSENGER_COUNT,
        TRIP_DISTANCE::NUMBER(10,2) AS TRIP_DISTANCE,
        PICKUP_LONGITUDE::NUMBER(18,15) AS PICKUP_LONGITUDE,
        PICKUP_LATITUDE::NUMBER(18,15) AS PICKUP_LATITUDE,
        RATECODE_ID::NUMBER(38,0) AS RATECODE_ID,
        STORE_AND_FWD_FLAG,
        DROPOFF_LONGITUDE::NUMBER(18,15) AS DROPOFF_LONGITUDE,
        DROPOFF_LATITUDE::NUMBER(18,15) AS DROPOFF_LATITUDE,
        PAYMENT_TYPE::NUMBER(3,0) AS PAYMENT_TYPE,
        PAYMENT_TYPE_NAME,
        FARE_AMOUNT::NUMBER(10,2) AS FARE_AMOUNT,
        EXTRA::NUMBER(10,2) AS EXTRA,
        MTA_TAX::NUMBER(10,2) AS MTA_TAX,
        TIP_AMOUNT::NUMBER(10,2) AS TIP_AMOUNT,
        TOLLS_AMOUNT::NUMBER(10,2) AS TOLLS_AMOUNT,
        IMPROVEMENT_SURCHARGE::NUMBER(10,2) AS IMPROVEMENT_SURCHARGE,
        TOTAL_AMOUNT::NUMBER(10,2) AS TOTAL_AMOUNT,
        TRIP_DURATION_MINUTES::NUMBER(4,0) AS TRIP_DURATION_MINUTES,
        TRIP_SPEED_MPH::NUMBER(5,2) AS TRIP_SPEED_MPH,
        CREATED_TIMESTAMP::TIMESTAMP_NTZ(9) AS CREATED_TIMESTAMP
    FROM {{ source('taxi_trips', 'taxi_trips_raw') }}
),

STG_SOURCE_WITH_MANDATORY_FIELDS AS (
    SELECT * FROM STG_SOURCE
    WHERE
        NOT ((PICKUP_LONGITUDE IS NULL OR PICKUP_LONGITUDE = 0)
            AND (PICKUP_LATITUDE IS NULL OR PICKUP_LATITUDE = 0))
        AND NOT ((DROPOFF_LONGITUDE IS NULL OR DROPOFF_LONGITUDE = 0)
            AND (DROPOFF_LATITUDE IS NULL OR DROPOFF_LATITUDE = 0))
        AND NOT TPEP_DROPOFF_DATETIME IS NULL
),

STG_SOURCE_CLEANED AS (
    SELECT
        COALESCE(VENDOR_ID, '1') AS VENDOR_ID,
        CASE
            WHEN (TPEP_PICKUP_DATETIME IS NULL OR TPEP_PICKUP_DATETIME > TPEP_DROPOFF_DATETIME) AND TRIP_DISTANCE > 0
                THEN DATEADD(MINUTE, -(TRIP_DISTANCE * 5), TPEP_DROPOFF_DATETIME)
            WHEN TPEP_PICKUP_DATETIME > TPEP_DROPOFF_DATETIME
                THEN '{{ var('default_date') }}'
            ELSE COALESCE(TPEP_PICKUP_DATETIME, '{{ var('default_date') }}')
        END AS TPEP_PICKUP_DATETIME,
        TPEP_DROPOFF_DATETIME,
        PASSENGER_COUNT,
        TRIP_DISTANCE,
        PICKUP_LONGITUDE,
        PICKUP_LATITUDE,
        RATECODE_ID,
        STORE_AND_FWD_FLAG,
        DROPOFF_LONGITUDE,
        DROPOFF_LATITUDE,
        PAYMENT_TYPE,
        PAYMENT_TYPE_NAME,
        FARE_AMOUNT,
        EXTRA,
        MTA_TAX,
        TIP_AMOUNT,
        TOLLS_AMOUNT,
        IMPROVEMENT_SURCHARGE,
        TOTAL_AMOUNT,
        TRIP_DURATION_MINUTES,
        TRIP_SPEED_MPH,
        CREATED_TIMESTAMP
    FROM STG_SOURCE_WITH_MANDATORY_FIELDS
)

SELECT * FROM STG_SOURCE_CLEANED
{% if is_incremental() %}
WHERE CREATED_TIMESTAMP > (
    SELECT COALESCE(MAX(CREATED_TIMESTAMP), '{{ var('default_date') }}')
    FROM {{ source('taxi_trips', 'taxi_trips_consistent') }}
)
{% endif %}
