WITH AGGREGATED_TRIP_VOLUME AS (
    SELECT
        D.WEEK_OF_THE_YEAR AS WEEK,
        D.MONTH,
        D.YEAR,
        COUNT(F.TRIP_ID) AS TRIP_VOLUME
    FROM {{ ref('fact_taxi_trips') }} F
    JOIN {{ ref('dim_date') }} D
        ON F.PICKUP_DATE_ID = D.DATE_ID
    GROUP BY WEEK, MONTH, YEAR
)

SELECT
    WEEK,
    MONTH,
    YEAR,
    TRIP_VOLUME,
    LAG(TRIP_VOLUME, 1, 0) OVER (PARTITION BY YEAR ORDER BY WEEK) AS PREVIOUS_TRIP_VOLUME,
    CASE
        WHEN PREVIOUS_TRIP_VOLUME = 0 THEN 0
        ELSE ROUND(((TRIP_VOLUME - PREVIOUS_TRIP_VOLUME) / PREVIOUS_TRIP_VOLUME) * 100, 2)
    END AS  WOW_GROWTH_RATE
FROM AGGREGATED_TRIP_VOLUME
