name: 'Terraform Command'
inputs:
  command:
    required: true
    default: 'plan'
env:
  SNOWFLAKE_PASSWORD: ${{secrets.SNOWFLAKE_PASSWORD}}
runs:
  using: 'composite'
  steps:
  - name: Run Terraform Command
    run: cd terraform && terraform plan -input=false